---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/integration

inputs:
  - name: ci
  - name: infrastructure
  - name: director-creds

outputs:
  - name: bats-config

params:
  cpi_source_branch:
  google_subnetwork_range:
  stemcell_name:
  private_key_data:
  public_key_data:

run:
  path: ci/ci/tasks/prepare-bats-config.sh
