---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: foundationalinfrastructure/gce-cpi-release
inputs:
  - name: bosh-google-cpi-release
  - name: ci
run:
  path: ci/ci/tasks/unit-tests.sh
