---
groups:
  - name: light-gce-stemcells
    jobs:
      - ubuntu-trusty-stemcell-latest
      - ubuntu-trusty-stemcell-3312
      - ubuntu-trusty-stemcell-3263

shared:
  - &get-cpi-src
    get: bosh-cpi-src
    trigger: false
  - &get-bosh-cli
    get: bosh-cli
    trigger: false
  - &get-cpi-release
    get: bosh-cpi-release
    trigger: false
  - &create-light-stemcell
    task: create-light-stemcell
    file: bosh-cpi-src/ci/stemcell/light/tasks/build-light-stemcell.yml
    params:
      BUCKET_NAME:     {{google_raw_stemcells_bucket_name}}
  - &upload-raw-stemcells
    aggregate:
    - put: bosh-ubuntu-raw-stemcells
      params:
        file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz
        predefined_acl: "publicRead"
    - put: bosh-ubuntu-raw-stemcells-sha1
      params:
        file: raw-stemcell/bosh-stemcell-*-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1
        predefined_acl: "publicRead"
  - &verify-stemcell-boots
    do:
    - put: terraform
      params:
        generate_random_name: true
        terraform_source: bosh-cpi-src/ci/stemcell/light/terraform/
    - task: deploy-skeletal
      file: bosh-cpi-src/ci/stemcell/light/tasks/deploy-skeletal.yml
      params:
        SSH_PRIVATE_KEY: {{ssh_private_key}}
        GCE_CREDENTIALS_JSON: {{gce_credentials_json}}
    - task: publish-stemcell-and-checksum
      file: bosh-cpi-src/ci/stemcell/light/tasks/publish-stemcell-and-checksum.yml
      params:
        BOSHIO_TOKEN: {{google_boshio_checksum_token}}
        AWS_ACCESS_KEY_ID: {{google_light_stemcells_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{google_light_stemcells_secret_access_key}}
        AWS_DEFAULT_REGION: {{google_light_stemcells_region}}
        AWS_ENDPOINT: {{google_light_stemcells_endpoint}}
        OUTPUT_BUCKET: {{google_light_stemcells_bucket_name}}
    ensure:
      task: destroy-skeletal
      file: bosh-cpi-src/ci/stemcell/light/tasks/destroy-skeletal.yml
      ensure:
        put: terraform
        params:
          env_name_file: terraform/name
          terraform_source: bosh-cpi-src/ci/stemcell/light/terraform/
          action: destroy
        get_params:
          action: destroy

jobs:
  - name: ubuntu-trusty-stemcell-latest
    plan:
      - aggregate:
        - get: stemcell
          resource: ubuntu-stemcell-latest
          trigger: true
          version: every
          params:
            preserve_filename: true
        - *get-cpi-src
        - *get-bosh-cli
        - *get-cpi-release
      - *create-light-stemcell
      - *upload-raw-stemcells
      - *verify-stemcell-boots

  - name: ubuntu-trusty-stemcell-3312
    plan:
      - aggregate:
        - get: stemcell
          resource: ubuntu-stemcell-3312
          trigger: true
          version: every
          params:
            preserve_filename: true
        - *get-cpi-src
        - *get-bosh-cli
        - *get-cpi-release
      - *create-light-stemcell
      - *upload-raw-stemcells
      - *verify-stemcell-boots

  - name: ubuntu-trusty-stemcell-3263
    plan:
      - aggregate:
        - get: stemcell
          resource: ubuntu-stemcell-3263
          trigger: true
          version: every
          params:
            preserve_filename: true
        - *get-cpi-src
        - *get-bosh-cli
        - *get-cpi-release
      - *create-light-stemcell
      - *upload-raw-stemcells
      - *verify-stemcell-boots

resources:
  - name: bosh-cli
    type: s3
    source:
      bucket: bosh-cli-artifacts
      regexp: bosh-cli-(\d+\.\d+\.\d+)-linux-amd64

  - name: bosh-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-google-cpi-release

  - name: bosh-cpi-src
    type: git
    source:
      # TODO: change this back before submitting PR!!!!!
      uri: https://github.com/cloudfoundry-incubator/bosh-google-cpi-release.git
      # branch: master
      branch: PR-version-family

  - name: terraform
    type: terraform
    source:
      storage:
        bucket: {{terraform_bucket_name}}
        bucket_path: stemcell-ci-terraform/
        access_key_id: {{terraform_bucket_access_key}}
        secret_access_key: {{terraform_bucket_secret_key}}
        endpoint: storage.googleapis.com
      vars:
        gce_project_id: {{gce_project_id}}
        gce_credentials_json: {{gce_credentials_json}}

  - name: ubuntu-stemcell-latest
    type: bosh-io-stemcell-version-family
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      force_regular: true

  - name: ubuntu-stemcell-3312
    type: bosh-io-stemcell-version-family
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3312"

  - name: ubuntu-stemcell-3263
    type: bosh-io-stemcell-version-family
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent
      force_regular: true
      version_family: "3263"

  - name: bosh-ubuntu-raw-stemcells
    type: gcs-resource
    source:
      json_key: {{gce_credentials_json}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz

  - name: bosh-ubuntu-raw-stemcells-sha1
    type: gcs-resource
    source:
      json_key: {{gce_credentials_json}}
      bucket:   {{google_raw_stemcells_bucket_name}}
      regexp:   bosh-stemcell-([0-9\.]+)-google-kvm-ubuntu-trusty-go_agent-raw.tar.gz.sha1

resource_types:
  - name: gcs-resource
    type: docker-image
    source:
      repository: frodenas/gcs-resource
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
  # TODO: switch back to using canonical resource after PR is merged #133222913
  - name: bosh-io-stemcell-version-family
    type: docker-image
    source:
      repository: boshcpi/bosh-io-stemcell-resource
      tag: PR-version-family
