#!/usr/bin/env bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PROJECT_RUBY_VERSION=$(< "${script_dir}/../.ruby-version")

if [[ ! -f /usr/local/share/chruby/chruby.sh ]]; then
  brew install chruby
fi
source /usr/local/share/chruby/chruby.sh

chruby "${PROJECT_RUBY_VERSION}"
if [[ $? -eq 1 ]]; then
  echo "Ruby version ${PROJECT_RUBY_VERSION} not found. Installing..."

  which "ruby-install" > /dev/null 2>&1
  if [[ $? -eq 1 ]]; then
    brew install ruby-install
  fi

  echo "Installing Ruby version ${PROJECT_RUBY_VERSION} ..."
  ruby-install "ruby" "${PROJECT_RUBY_VERSION}"
  chruby "${PROJECT_RUBY_VERSION}"

  echo "Ruby version ${PROJECT_RUBY_VERSION} successfully installed."
fi
echo "Using ruby version ${PROJECT_RUBY_VERSION}"

echo "Installing bundler..."
gem install "bundler"
